language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=v2.8
  - SYMFONY_VERSION=origin/master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php -d memory_limit=-1 composer.phar install

script: phpunit
